import React, { useEffect, useRef } from 'react';
import { Stage, Layer } from 'react-konva';
import Konva from 'konva';
import { GrafcetDiagram } from '../../models/types';
import Step from '../Elements/Step';
import Transition from '../Elements/Transition';
import Connection from '../Elements/Connection';
import Gate from '../Elements/Gate';
import ActionBlock from '../Elements/ActionBlock';
import { getDiagramImage } from '../../utils/exportUtils';

interface SfcThumbnailRendererProps {
    diagram: GrafcetDiagram;
    onRendered: (imageData: string) => void;
}

/**
 * A hidden renderer that takes a GrafcetDiagram and generates a PNG base64 string.
 * This is used to generate previews for SFCs generated by agents.
 */
const SfcThumbnailRenderer: React.FC<SfcThumbnailRendererProps> = ({ diagram, onRendered }) => {
    const stageRef = useRef<Konva.Stage>(null);

    useEffect(() => {
        const renderImage = async () => {
            if (!stageRef.current) return;

            try {
                // Wait a small bit for Konva to initialize the layer
                await new Promise(resolve => setTimeout(resolve, 100));

                const imageData = await getDiagramImage(stageRef.current, {
                    hideGrid: true,
                    whiteBackground: true,
                    cropToContent: true,
                    pixelRatio: 2
                });

                onRendered(imageData);
            } catch (error) {
                console.error('Error rendering SFC thumbnail:', error);
            }
        };

        renderImage();
    }, [diagram, onRendered]);

    // We render this off-screen or hidden
    return (
        <div style={{ position: 'absolute', left: '-9999px', top: '-9999px', visibility: 'hidden', pointerEvents: 'none' }}>
            <Stage
                width={1000}
                height={1000}
                ref={stageRef}
            >
                <Layer>
                    {diagram.elements.map((element: any) => {
                        switch (element.type) {
                            case 'step':
                                return <Step key={element.id} step={element} />;
                            case 'transition':
                                return <Transition key={element.id} transition={element} />;
                            case 'connection':
                                return <Connection key={element.id} connection={element} />;
                            case 'and-gate':
                            case 'or-gate':
                                return <Gate key={element.id} gate={element} />;
                            case 'action-block':
                                return <ActionBlock key={element.id} actionBlock={element} />;
                            default:
                                return null;
                        }
                    })}
                </Layer>
            </Stage>
        </div>
    );
};

export default SfcThumbnailRenderer;
